version: '3'

services:
    nginx:
        build: 
            context: .
            dockerfile: Dockerfile_nginx
        image: nginx:0.1
        ports: 
            - "80:80"
        container_name: nginx1
        networks: 
            - default 

networks:
    default:
        external:
             name: bridge
