version: '3'

services:
    nginx:
        build: 
            context: .
            dockerfile: Dockerfile_nginx
        image: nginx:webserver
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf:ro
        ports: 
            - "8080:80"
        environment: 
            - NGINX_PORT=80
            command: [nginx-debug, '-g', 'daemon off;']
        container_name: nginx_webserver
        networks:
            - backend

networks:
    backend:
        driver: bridge