version: '3'

services:
    nginx:
        build:
            context: .
            dockerfile: Dockerfile.nginx
        ports: 
            - "80:80"
        container_name: nginx
        links:
            - springproject_blue
            - springproject_green
        networks:
            - backend


