version: '3'

services:
    nginx:
        build: 
            context: .
            dockerfile: Dockerfile_nginx
        image: nginx:webserver
        volumes: 
            - /data:/data
            - /var/log/nginx:/var/log/nginx
        ports: 
            - "80:80"
        container_name: nginx_webserver
        networks:
            - backend

networks:
    backend:
        driver: bridge