version: '3'

services:
    nginx:
#        build: 
#            context: .
#            dockerfile: Dockerfile_nginx
        image: nginx
        volumes:
            - ./nginx/conf.d:/etc/nginx/conf.d
        ports: 
            - "80:80"
        container_name: nginx_webserver
        networks:
            - backend

networks:
    backend:
        driver: bridge